sudo: required
services:
 - docker

before_install:
 - docker build -t surendusuresh/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true surendusuresh/docker-react npm run test

deploy:
 provider: elasticbeanstalk
 region: "ap-south-1"
 app: "docker-react"
 env: "Dockerreact-env"
 bucket_name: "elasticbeanstalk-ap-south-1-348053309847"
 bucket_path: "docker-react"
 on:
  branch: master
 access_key_id: "$AWS_ACCESS_KEY"
 secret_access_key: "$AWS_SECRET_KEY"
